# -*- coding: utf-8 -*-
"""4지선다 문제은행 (60문항).

choices의 첫 번째 보기가 정답이다. 앱에서 퀴즈를 시작할 때 보기 순서를 섞는다.
"""
import hashlib

CATEGORIES = ["LangChain · LCEL", "RAG", "LangGraph 기본", "LangGraph 심화", "Agent · 응용"]


def _q(cat, question, choices, explanation):
    return {"cat": cat, "q": question, "choices": choices, "exp": explanation}


_LC, _RAG, _LG, _ADV, _AG = CATEGORIES

QUESTIONS = [
    # ── LangChain · LCEL (11) ─────────────────────────────────────────
    _q(_LC, "LangChain의 주된 역할로 가장 알맞은 것은?",
       ["LLM 관련 구성요소를 연결해 애플리케이션 파이프라인을 구성한다",
        "LLM 모델의 가중치를 직접 학습시키는 딥러닝 프레임워크이다",
        "임베딩 벡터를 저장하는 전용 데이터베이스이다",
        "웹페이지를 수집하는 크롤링 전용 도구이다"],
       "LangChain은 Prompt, Model, Parser, Retriever 같은 부품을 이어 붙여 LLM 앱을 만드는 프레임워크예요. 모델 학습이나 벡터 저장 자체가 목적은 아니에요."),
    _q(_LC, "LCEL에서 구성요소를 연결할 때 쓰는 기호는?",
       ["|", "&", ">>", "+"],
       "chain = prompt | model | parser 처럼 파이프(|)로 연결하고, 앞 단계 출력이 뒤 단계 입력으로 넘어가요."),
    _q(_LC, "chain = prompt | model | parser 에서 parser가 입력으로 받는 것은?",
       ["모델이 돌려준 AIMessage", "사용자가 넣은 dict", "빈칸이 채워진 프롬프트", "최종 str"],
       "흐름은 dict → PromptTemplate → ChatModel → AIMessage → Parser → str 이에요. parser는 모델 출력인 AIMessage를 받아요."),
    _q(_LC, "StrOutputParser의 역할은?",
       ["AIMessage에서 본문 문자열만 뽑아 str로 바꾼다",
        "긴 문서를 청크로 나눈다",
        "프롬프트의 빈칸에 변수를 채운다",
        "검색 결과를 관련도 순으로 재정렬한다"],
       "ChatModel의 출력은 메타데이터가 붙은 AIMessage 객체라서, StrOutputParser로 본문 문자열만 꺼내요."),
    _q(_LC, "일반 Python 함수를 체인 중간에 넣을 수 있도록 Runnable로 감싸는 클래스는?",
       ["RunnableLambda", "RunnablePassthrough", "StrOutputParser", "PromptTemplate"],
       "RunnableLambda(clean_text)처럼 내가 만든 함수를 Runnable로 만들어 | 로 연결할 수 있게 해요."),
    _q(_LC, "RunnablePassthrough의 역할로 옳은 것은?",
       ["입력을 바꾸지 않고 그대로 다음 단계로 전달한다",
        "Python 함수를 Runnable로 변환한다",
        "모델 출력을 JSON으로 파싱한다",
        "그래프를 실행 가능한 객체로 컴파일한다"],
       "RAG에서 {\"context\": retriever, \"question\": RunnablePassthrough()}처럼 검색은 하면서 원래 질문도 그대로 들고 갈 때 써요."),
    _q(_LC, "Runnable에 대한 설명으로 옳은 것은?",
       ["LangChain 구성요소들의 공통 실행 규격으로, invoke()로 실행하고 | 로 연결할 수 있다",
        "Vector DB의 한 종류이다",
        "LLM 모델만 Runnable이 될 수 있다",
        "그래프 Node 사이의 조건 분기를 담당하는 함수이다"],
       "Prompt, Model, Parser, Retriever가 모두 Runnable이라서 같은 방식으로 실행하고 연결할 수 있어요."),
    _q(_LC, "PromptTemplate이 일반적으로 입력으로 받는 것은?",
       ["빈칸 이름과 값을 담은 dict", "AIMessage", "임베딩 벡터", "컴파일된 그래프"],
       "{\"question\": \"...\"}처럼 키 이름이 프롬프트의 빈칸({question})과 맞는 dict를 받아 완성된 프롬프트를 만들어요."),
    _q(_LC, "Output Parser가 필요한 이유로 가장 알맞은 것은?",
       ["모델 출력을 문자열, JSON, 객체 등 쓰기 좋은 형태로 바꾸기 위해",
        "모델 응답 속도를 높이기 위해",
        "관련 문서를 검색하기 위해",
        "텍스트를 벡터로 바꾸기 위해"],
       "모델은 메시지 객체를 돌려주므로, 다음 단계나 화면에서 쓰기 좋은 형태로 변환하는 부품이 Parser예요."),
    _q(_LC, "LangChain의 Runnable이나 LangGraph의 컴파일된 그래프를 한 번 실행할 때 쓰는 메서드는?",
       ["invoke()", "execute()", "run_graph()", "start()"],
       "체인과 컴파일된 그래프 모두 Runnable이라 invoke()로 실행해요."),
    _q(_LC, "LangChain 부품과 역할의 연결이 잘못된 것은?",
       ["Retriever – 모델 출력을 JSON으로 변환",
        "Prompt – 모델에게 어떤 형식으로 지시할지 결정",
        "Model – 실제로 답을 생성하는 LLM",
        "Parser – 모델 출력을 원하는 형태로 변환"],
       "Retriever는 질문을 받아 관련 문서를 가져오는 부품이에요. 출력 변환은 Parser의 일이에요."),

    # ── RAG (15) ──────────────────────────────────────────────────────
    _q(_RAG, "RAG의 핵심 목적은?",
       ["외부 정보를 검색해 LLM 답변 생성에 활용한다",
        "LLM의 파라미터를 새 데이터로 다시 학습시킨다",
        "텍스트로 이미지를 생성한다",
        "자주 묻는 답변을 캐시해 속도를 높인다"],
       "Retrieval-Augmented Generation, 즉 검색으로 근거를 가져와 생성에 보태는 방식이에요. 모델을 재학습하지 않아요."),
    _q(_RAG, "RAG 사전 준비(인덱싱) 단계의 순서로 옳은 것은?",
       ["Loader → Chunking → Embedding → Vector DB 저장",
        "Embedding → Loader → Chunking → Vector DB 저장",
        "Chunking → Loader → Vector DB 저장 → Embedding",
        "Vector DB 저장 → Embedding → Chunking → Loader"],
       "문서를 불러오고(Loader), 나누고(Chunking), 벡터로 바꾼 뒤(Embedding), 저장해요(Vector DB)."),
    _q(_RAG, "Document Loader의 역할은?",
       ["PDF, 웹페이지, txt 등을 LangChain Document 형태로 불러온다",
        "문서를 의미 벡터로 변환한다",
        "검색 결과를 다시 평가해 순위를 바꾼다",
        "답변이 근거에 충실한지 검사한다"],
       "Loader는 원본 파일을 읽어 page_content와 metadata를 가진 Document 객체로 바꿔요."),
    _q(_RAG, "LangChain Document 객체가 가지는 두 가지 주요 속성은?",
       ["page_content와 metadata", "question과 answer", "node와 edge", "vector와 reducer"],
       "page_content는 본문, metadata는 출처나 페이지 번호 같은 부가 정보예요."),
    _q(_RAG, "긴 문서를 작은 청크로 나누는 가장 큰 이유는?",
       ["질문과 관련된 부분을 더 정확하게 검색하기 위해",
        "저장 용량을 일부러 늘리기 위해",
        "임베딩 단계를 생략하기 위해",
        "LLM을 재학습할 데이터를 만들기 위해"],
       "문서를 통째로 검색하면 질문과 상관없는 내용까지 섞이고 LLM 입력 길이에도 한계가 있어서 잘라요."),
    _q(_RAG, "대표적인 청킹(텍스트 분할) 클래스는?",
       ["RecursiveCharacterTextSplitter", "StrOutputParser", "StateGraph", "RunnableLambda"],
       "문단 → 줄 → 공백 → 글자 순으로 큰 단위부터 잘라 보면서 의미 덩어리를 최대한 유지해요."),
    _q(_RAG, "chunk_overlap을 설정하는 목적은?",
       ["청크 경계에서 문장이 잘려 문맥이 끊기는 것을 막기 위해",
        "청크 개수를 최대한 줄이기 위해",
        "중복된 문서를 자동으로 삭제하기 위해",
        "검색 결과를 재정렬하기 위해"],
       "이웃한 청크끼리 일부(예: 150자)를 겹치게 두어 경계의 의미가 사라지지 않게 해요."),
    _q(_RAG, "Embedding에 대한 설명으로 옳은 것은?",
       ["텍스트를 의미를 반영한 숫자 벡터로 변환하는 것",
        "문서를 여러 조각으로 자르는 것",
        "모델 출력을 문자열로 바꾸는 것",
        "그래프의 State를 저장하는 것"],
       "뜻이 비슷한 문장은 벡터 공간에서도 가까워지기 때문에 의미 기반 검색이 가능해져요."),
    _q(_RAG, "Vector DB의 역할은?",
       ["벡터를 저장하고 질문 벡터와 유사한 벡터를 찾는다",
        "프롬프트 템플릿을 보관한다",
        "LLM의 응답을 사람이 승인하도록 멈춘다",
        "병렬 Node의 결과를 합친다"],
       "FAISS, Chroma, Pinecone 같은 Vector DB는 벡터 저장과 유사도 검색을 맡아요."),
    _q(_RAG, "질문이 들어왔을 때 Vector DB에서 검색하기 전에 질문을 어떻게 처리하는가?",
       ["문서와 같은 임베딩 모델로 질문을 벡터로 바꾼다",
        "질문을 청크로 잘게 나눈다",
        "질문을 바로 Reranking 모델에 넣는다",
        "질문을 StrOutputParser로 파싱한다"],
       "문서 벡터와 비교하려면 질문도 같은 임베딩 모델로 벡터화해야 해요."),
    _q(_RAG, "Retriever에 대한 설명으로 옳은 것은?",
       ["질문을 받아 관련 문서를 가져오는 인터페이스이다",
        "텍스트를 숫자 벡터로 바꾸는 모델이다",
        "그래프 흐름을 설계하는 빌더 클래스이다",
        "모델 출력을 JSON으로 바꾸는 파서이다"],
       "retriever.invoke(질문) → 관련 Document 목록. 비유하면 도서관 사서예요."),
    _q(_RAG, "Reranking의 역할은?",
       ["1차 검색 결과를 다시 평가해 진짜 관련도 높은 문서를 위로 올린다",
        "문서를 다시 청킹한다",
        "임베딩 모델을 재학습한다",
        "답변을 여러 번 생성해 가장 긴 것을 고른다"],
       "벡터 검색은 빠르지만 대략적이라, 더 정밀한 모델로 후보를 다시 점수 매겨 순서를 바꿔요."),
    _q(_RAG, "검색된 관련 청크는 생성 단계에서 어디에 들어가는가?",
       ["프롬프트의 Context 자리", "모델의 가중치", "Parser의 설정값", "State의 Reducer"],
       "찾은 청크를 프롬프트의 {context}에 넣어 LLM이 그 근거로 답하게 해요."),
    _q(_RAG, "RAG 답변이 틀렸을 때 가장 먼저 할 디버깅 접근은?",
       ["검색이 틀린 것인지, 검색은 맞았는데 생성이 틀린 것인지 나눠서 확인한다",
        "무조건 더 큰 LLM으로 교체한다",
        "chunk_size를 무조건 크게 늘린다",
        "Vector DB를 삭제하고 처음부터 다시 만든다"],
       "검색 오류면 청킹·임베딩·검색 설정을, 생성 오류면 프롬프트·모델을 손봐야 해서 원인을 먼저 나눠요."),
    _q(_RAG, "관련 문서는 정확히 검색됐는데 답변이 틀렸다면 우선 점검할 부분은?",
       ["프롬프트와 생성(Generation) 단계", "Loader", "Chunking", "Embedding 모델"],
       "검색은 맞았으니 생성 오류예요. 근거를 어떻게 쓰라고 지시했는지(프롬프트)나 모델을 점검해요."),

    # ── LangGraph 기본 (14) ───────────────────────────────────────────
    _q(_LG, "LangGraph를 사용하는 주된 이유는?",
       ["조건, 분기, 반복, 병렬 등 복잡한 실행 흐름을 제어하기 위해",
        "텍스트를 벡터로 바꾸기 위해",
        "PDF를 Document로 불러오기 위해",
        "모델 출력을 문자열로 파싱하기 위해"],
       "'다음에 무엇을 실행할지'가 일직선이 아닐 때 흐름을 그래프로 설계하려고 써요."),
    _q(_LG, "LangGraph의 3대 구성요소는?",
       ["State, Node, Edge", "Prompt, Model, Parser", "Loader, Embedding, Retriever", "Agent, Tool, Memory"],
       "State(공유 데이터), Node(작업), Edge(다음으로 가는 길)가 그래프의 기본 단위예요."),
    _q(_LG, "LangGraph에서 State란?",
       ["그래프 전체에서 공유되는 데이터", "실제로 실행되는 함수", "Node 사이의 연결선", "그래프를 컴파일하는 메서드"],
       "모든 Node가 같은 State를 읽고 자기 결과를 State에 써요. 비유하면 가방이에요."),
    _q(_LG, "LangGraph에서 Node란?",
       ["실제로 작업을 수행하는 단위(보통 Python 함수)", "그래프 전체가 공유하는 데이터", "실행 흐름의 연결선", "병렬 결과 병합 규칙"],
       "Node는 State를 받아 일을 하고 바뀐 부분을 돌려주는 작업실이에요."),
    _q(_LG, "LangGraph에서 Edge란?",
       ["Node 사이의 실행 흐름(다음에 어디로 갈지)", "State의 구조 정의", "검색된 문서 목록", "체크포인트 저장소"],
       "Edge는 작업실 사이의 길이에요. 고정 Edge와 조건부 Edge가 있어요."),
    _q(_LG, "State · Node · Edge를 비유한 것으로 옳은 것은?",
       ["가방 · 작업실 · 길", "길 · 가방 · 작업실", "작업실 · 길 · 가방", "가방 · 길 · 작업실"],
       "State는 들고 다니는 가방, Node는 일하는 작업실, Edge는 작업실 사이의 길이에요."),
    _q(_LG, "LangGraph에서 TypedDict를 쓰는 목적은?",
       ["State에 어떤 키와 타입이 들어가는지 구조를 정의하기 위해",
        "병렬 결과를 합치는 규칙을 정하기 위해",
        "그래프를 실행 가능한 객체로 바꾸기 위해",
        "조건에 따라 다음 Node를 고르기 위해"],
       "class State(TypedDict): question: str ... 처럼 State 구조를 명확히 선언해요."),
    _q(_LG, "StateGraph에 대한 설명으로 옳은 것은?",
       ["State 타입을 받아 그래프를 설계하는 빌더 클래스이다",
        "검색 결과를 재정렬하는 모델이다",
        "그래프 실행 결과를 저장하는 데이터베이스이다",
        "모델 출력을 파싱하는 클래스이다"],
       "builder = StateGraph(State)로 만들고 여기에 Node와 Edge를 등록해요."),
    _q(_LG, "add_edge(\"retrieve\", \"generate\")의 의미는?",
       ["retrieve 다음에는 항상 generate를 실행한다",
        "조건이 맞을 때만 generate를 실행한다",
        "retrieve와 generate를 동시에 실행한다",
        "generate Node를 새로 등록한다"],
       "일반 Edge는 고정된 길이라 항상 같은 다음 Node로 가요."),
    _q(_LG, "add_conditional_edges()의 역할은?",
       ["조건(라우팅 함수의 결과)에 따라 다음 Node를 다르게 선택한다",
        "항상 같은 다음 Node로 연결한다",
        "새로운 Node를 그래프에 추가한다",
        "설계한 그래프를 컴파일한다"],
       "앞 Node가 끝나면 라우팅 함수를 실행해 그 반환값으로 갈 곳을 정하는 갈림길이에요."),
    _q(_LG, "add_conditional_edges(\"check\", route_fn)에서 route_fn이 하는 일은?",
       ["State를 보고 다음에 갈 곳을 나타내는 값을 반환한다",
        "검색된 문서를 State에 추가한다",
        "State 구조를 정의한다",
        "병렬 Node의 결과를 합친다"],
       "예를 들어 검색이 필요하면 \"search\", 아니면 \"direct\"를 반환해 다음 Node를 고르게 해요."),
    _q(_LG, "compile()의 역할은?",
       ["설계한 그래프를 실행 가능한 객체로 변환한다",
        "State에 새 키를 추가한다",
        "검색 결과를 벡터로 바꾼다",
        "Node 하나를 단독으로 실행한다"],
       "graph = builder.compile() 후 graph.invoke(...)로 실행해요."),
    _q(_LG, "LangGraph로 그래프를 만들고 실행하는 순서로 옳은 것은?",
       ["State 정의 → StateGraph 생성 → add_node → add_edge → compile() → invoke()",
        "StateGraph 생성 → compile() → State 정의 → add_node → invoke()",
        "add_node → State 정의 → invoke() → compile()",
        "compile() → add_edge → add_node → State 정의 → invoke()"],
       "구조를 정의하고, 설계하고, 컴파일한 뒤 실행해요."),
    _q(_LG, "retrieve_node가 검색 결과를 State에 반영할 때 일반적으로 반환하는 것은?",
       ["바꿀 키만 담은 dict (예: {\"context\": docs})",
        "다음에 실행할 Node의 이름",
        "항상 비어 있는 None",
        "컴파일된 그래프 객체"],
       "Node는 State 전체가 아니라 바꿀 부분만 돌려주고, LangGraph가 이를 기존 State에 합쳐요."),

    # ── LangGraph 심화 (10) ───────────────────────────────────────────
    _q(_ADV, "Fan-out의 의미는?",
       ["하나의 Node에서 여러 Node로 동시에 분기한다",
        "여러 Node의 결과가 하나로 합류한다",
        "State를 특정 시점에 저장한다",
        "질문을 검색하기 좋게 다시 쓴다"],
       "부채가 펼쳐지듯 하나에서 여러 갈래로 나가는 병렬 분기예요."),
    _q(_ADV, "Fan-in의 의미는?",
       ["여러 Node의 결과가 하나의 Node로 다시 합류한다",
        "하나의 Node가 여러 Node로 분기한다",
        "사람이 중간에 승인한다",
        "그래프를 실행 가능한 객체로 바꾼다"],
       "병렬로 갈라졌던 결과가 합치기 Node로 모이는 것이 Fan-in이에요."),
    _q(_ADV, "다음 중 LangGraph의 병렬 실행과 관계없는 용어는?",
       ["Crossfade", "Fan-out", "Fan-in", "Reducer"],
       "Crossfade는 영상/오디오가 겹치며 전환되는 효과를 뜻해요. 병렬 합류는 Fan-in이에요."),
    _q(_ADV, "Reducer가 필요한 이유는?",
       ["병렬 Node들이 같은 State 필드를 업데이트할 때 어떻게 합칠지 정하기 위해",
        "그래프를 실행 가능한 객체로 바꾸기 위해",
        "문서를 작은 청크로 나누기 위해",
        "LLM이 사용할 도구를 등록하기 위해"],
       "같은 키에 여러 값이 동시에 들어오면 충돌하므로 병합 규칙이 필요해요."),
    _q(_ADV, "results: Annotated[list, operator.add] 일 때, 병렬 Node A가 [\"A\"], Node B가 [\"B\"]를 반환하면 results는?",
       ["두 리스트가 이어 붙여진 [\"A\", \"B\"]",
        "나중에 끝난 Node의 값만 남는다",
        "먼저 끝난 Node의 값만 남는다",
        "항상 빈 리스트가 된다"],
       "operator.add는 리스트에 + 를 적용하므로 [\"A\"] + [\"B\"] = [\"A\", \"B\"]가 돼요."),
    _q(_ADV, "State 키에 Reducer를 지정하지 않았을 때 기본 업데이트 방식은?",
       ["새 값으로 덮어쓴다", "기존 값과 자동으로 이어 붙인다", "기존 값과 평균을 낸다", "새 값을 무시한다"],
       "기본은 덮어쓰기라서, 병렬로 같은 키를 쓰는 경우엔 Reducer를 지정해야 결과를 모두 보존할 수 있어요."),
    _q(_ADV, "Checkpoint의 역할은?",
       ["특정 시점의 State를 저장해 이어서 실행하거나 복구할 수 있게 한다",
        "병렬 결과를 합친다",
        "검색 결과를 재정렬한다",
        "텍스트를 벡터로 바꾼다"],
       "compile(checkpointer=...)로 저장소를 붙이면 단계별 State가 저장돼요. 대화 기억(Memory)도 이 덕분이에요."),
    _q(_ADV, "Human-in-the-loop에 대한 설명으로 옳은 것은?",
       ["흐름 중간에 사람의 승인이나 수정을 받는 단계를 넣는 구조이다",
        "사람 대신 LLM이 모든 판단을 내리는 구조이다",
        "사람이 직접 임베딩 벡터를 계산하는 구조이다",
        "사람이 Vector DB를 수동으로 검색하는 구조이다"],
       "AI 초안 → 사람 승인? → 예: 다음 단계 / 아니오: 수정 Node. 멈춘 State는 Checkpoint로 보관돼요."),
    _q(_ADV, "LangGraph에서 '답변 검증 후 부족하면 다시 검색'하는 반복 흐름을 만드는 방법은?",
       ["조건부 Edge로 검증 결과에 따라 이전 Node로 되돌아가게 연결한다",
        "compile()을 여러 번 호출한다",
        "TypedDict 안에 while 문을 작성한다",
        "StrOutputParser를 두 번 연결한다"],
       "검증 Node 뒤에 add_conditional_edges를 두고 '부족함'이면 질문 수정/검색 Node로, '좋음'이면 END로 보내요."),
    _q(_ADV, "재검색 루프가 무한히 반복되지 않도록 하는 일반적인 방법은?",
       ["State에 재시도 횟수를 저장하고, 상한을 넘으면 END로 라우팅한다",
        "chunk_overlap을 0으로 설정한다",
        "Reducer를 모두 제거한다",
        "compile()을 생략한다"],
       "retry_count 같은 값을 State에 두고 라우팅 함수에서 상한을 검사해요."),

    # ── Agent · 응용 (10) ────────────────────────────────────────────
    _q(_AG, "Agent에 대한 설명으로 옳은 것은?",
       ["LLM이 상황을 보고 다음에 어떤 행동(도구 사용 등)을 할지 판단하는 구조이다",
        "개발자가 정한 순서대로만 실행되는 구조이다",
        "문서를 벡터로 저장하는 데이터베이스이다",
        "모델 출력을 문자열로 바꾸는 파서이다"],
       "Agent는 행동 → 관찰 → 다시 판단을 반복하며 스스로 다음 행동을 고르는 작업자예요."),
    _q(_AG, "고정 Chain과 Agent의 차이로 옳은 것은?",
       ["고정 Chain은 정해진 순서로 실행되고, Agent는 LLM이 다음 행동을 판단한다",
        "고정 Chain은 LLM이 판단하고, Agent는 개발자가 순서를 정한다",
        "둘 다 항상 같은 순서로만 실행된다",
        "Agent는 LLM을 사용하지 않는다"],
       "고정 Chain은 개발자가, LangGraph Workflow는 개발자가 설계한 조건이, Agent는 LLM이 다음 행동을 정해요."),
    _q(_AG, "Agent가 사용하는 Tool에 대한 설명으로 옳은 것은?",
       ["검색, 계산기, DB 조회처럼 Agent가 호출할 수 있는 기능이다",
        "그래프의 State 구조를 정의하는 클래스이다",
        "병렬 결과를 합치는 규칙이다",
        "청크 사이의 겹침 길이이다"],
       "LLM은 어떤 Tool을 어떤 인자로 부를지 정하고, 실제 실행은 코드가 해요."),
    _q(_AG, "LangGraph Workflow에서 다음 단계를 결정하는 방식으로 가장 알맞은 것은?",
       ["개발자가 설계한 조건과 흐름에 따라 결정된다",
        "매번 무작위로 결정된다",
        "Vector DB의 유사도 점수만으로 결정된다",
        "항상 사용자가 직접 다음 Node를 입력한다"],
       "Workflow는 개발자가 Node·Edge·조건을 설계하고, 그 조건에 따라 길이 갈려요."),
    _q(_AG, "Query Rewrite의 의미는?",
       ["검색이 잘 되도록 사용자 질문을 다시 작성하는 것",
        "답변을 다른 언어로 번역하는 것",
        "검색된 문서의 순서를 바꾸는 것",
        "그래프 코드를 리팩터링하는 것"],
       "\"그거 위험해?\" → \"ELS 상품의 주요 투자 위험 요소\"처럼 검색하기 좋은 질문으로 고쳐 재검색해요."),
    _q(_AG, "RAG 답변의 Faithfulness 검사란?",
       ["답변이 검색된 근거 문서에 충실한지(지어낸 내용이 없는지) 확인하는 것",
        "답변의 글자 수가 충분한지 확인하는 것",
        "검색 속도가 충분히 빠른지 확인하는 것",
        "사용자가 답변에 만족했는지 설문하는 것"],
       "근거에 없는 내용을 만들어 내는 환각을 잡기 위한 검사예요. 통과하지 못하면 재생성해요."),
    _q(_AG, "LangGraph와 RAG를 함께 쓸 때의 장점이 아닌 것은?",
       ["모든 질문에 반드시 검색을 수행해야 한다",
        "검색 실패 시 자동으로 재검색할 수 있다",
        "질문을 검색하기 좋은 형태로 바꿀 수 있다",
        "답변을 검증한 뒤 부족하면 재생성할 수 있다"],
       "오히려 '검색이 필요한가?'를 판단해서 필요 없는 질문은 바로 답할 수 있다는 게 장점이에요."),
    _q(_AG, "고객 상담 챗봇에서 문의 유형(배송/환불/일반)에 따라 서로 다른 처리 Node로 보내려면 무엇을 쓰는 것이 가장 알맞은가?",
       ["add_conditional_edges()", "add_edge()만 여러 번", "chunk_overlap", "StrOutputParser"],
       "유형 분류 결과에 따라 갈 곳이 달라지므로 조건부 Edge(라우팅)가 필요해요."),
    _q(_AG, "멀티 Agent 시스템에서 Manager Agent의 역할은?",
       ["요청을 하위 Agent들에게 나눠 주고 결과를 합친다",
        "문서를 청크로 나눈다",
        "모든 Tool 호출을 막는다",
        "임베딩 모델을 학습시킨다"],
       "Research, Coding, Review Agent 등에게 일을 분배하고 결과를 모아 최종 답을 만드는 총괄 역할이에요(Supervisor)."),
    _q(_AG, "\"RAG는 무엇을 검색해서 답할지\"를 다룬다면, LangGraph는 무엇을 다루는가?",
       ["검색을 언제, 몇 번, 어떤 조건에서 할지 실행 흐름을 제어한다",
        "텍스트를 숫자 벡터로 바꾼다",
        "긴 문서를 작은 청크로 나눈다",
        "모델 출력을 문자열로 바꾼다"],
       "자료의 핵심 문장이에요. LangGraph는 검색 기능을 언제 쓰고 실패하면 어떻게 다시 할지를 제어해요."),
]

assert len(QUESTIONS) == 60, len(QUESTIONS)
assert all(len(q["choices"]) == 4 for q in QUESTIONS)

# 풀이 기록은 문제 id로 저장한다. 질문 문장에서 만들어서 문제 순서를 바꿔도 기록이 유지된다.
for _item in QUESTIONS:
    _item["id"] = hashlib.sha1(_item["q"].encode("utf-8")).hexdigest()[:10]

BY_ID = {q["id"]: q for q in QUESTIONS}
assert len(BY_ID) == len(QUESTIONS), "질문 문장이 중복됐어요"
