# -*- coding: utf-8 -*-
"""용어 정리 페이지에 쓰는 섹션별 용어 데이터.

각 섹션은 제목, 한 줄 요약(intro), (용어, 설명) 목록, 선택적으로 코드 예시와 흐름도를 가진다.
"""

SECTIONS = [
    {
        "id": "overview",
        "title": "큰 그림",
        "icon": ":material/hub:",
        "intro": "LangChain은 부품 조립, RAG는 검색해서 답하는 방법, LangGraph는 전체 흐름 제어를 맡아요.",
        "terms": [
            ("LLM", "대규모 언어 모델(Large Language Model). GPT나 Claude처럼 글을 읽고 써 주는 AI 모델 자체예요. 이것만으로는 한 번 묻고 한 번 답하는 일만 할 수 있어요."),
            ("LangChain", "LLM 앱에 필요한 부품(프롬프트, 모델, 출력 정리기, 검색기)을 같은 방식으로 이어 붙이게 해 주는 파이썬 프레임워크. 레고 블록과 블록을 끼우는 규칙이라고 생각하면 돼요."),
            ("RAG", "Retrieval-Augmented Generation(검색 증강 생성). 모델이 모르는 정보(사내 문서, 최신 자료)를 먼저 검색해 가져온 뒤, 그 내용을 근거로 답을 만드는 방식이에요. 라이브러리가 아니라 방법의 이름이에요."),
            ("LangGraph", "실행 흐름이 일직선이 아닐 때(조건 분기, 반복, 재시도, 병렬) 그 흐름을 그래프(점과 선)로 설계하고 실행하는 프레임워크. LangChain 팀이 만들었어요."),
        ],
        "flow": "사용자 질문\n  ↓\n[LangChain] Prompt / Model / Parser / Retriever 연결\n  ↓\n[RAG] 필요하면 외부 문서 검색\n  ↓\n[LangGraph] 검색할지, 재검색할지, 바로 답할지, 검증할지 흐름 제어\n  ↓\n최종 답변",
    },
    {
        "id": "langchain",
        "title": "LangChain 대표 부품",
        "icon": ":material/extension:",
        "intro": "LLM을 한 번 호출하는 것만으로는 앱을 만들기 어려워서, 여러 단계를 부품으로 나눠 연결해요.",
        "terms": [
            ("Prompt", "모델에게 주는 지시문. \"다음 문서를 참고해서 질문에 답해라: {context} 질문: {question}\"처럼 형식을 정해 둔 것이에요."),
            ("Model", "실제로 답을 생성하는 LLM. LangChain에서는 ChatOpenAI 같은 클래스로 감싸서 써요."),
            ("Parser (Output Parser)", "모델 출력은 메시지 객체로 나와요. 이걸 문자열, JSON, 파이썬 객체처럼 쓰기 좋은 형태로 바꿔 주는 부품이에요."),
            ("Retriever", "질문을 넣으면 관련 문서를 돌려주는 부품. 내부가 Vector DB든 웹 검색이든 바깥에서는 '질문 넣고 문서 받기'로 똑같이 써요."),
            ("Runnable", "LangChain에서 실행할 수 있는 모든 부품의 공통 규격. Prompt, Model, Parser, Retriever 전부 Runnable이라서 invoke()로 실행하고 | 로 연결할 수 있어요. 콘센트 규격이 같아서 어떤 플러그든 꽂히는 것과 비슷해요."),
        ],
    },
    {
        "id": "lcel",
        "title": "LCEL과 Runnable 흐름",
        "icon": ":material/link:",
        "intro": "chain = prompt | model | parser 에서 | 는 앞 단계 출력을 뒤 단계 입력으로 넘겨요.",
        "terms": [
            ("LCEL", "LangChain Expression Language. prompt | model | parser 처럼 파이프 기호로 부품을 이어 체인을 만드는 문법이에요."),
            ("| (파이프)", "왼쪽 단계의 출력을 오른쪽 단계의 입력으로 넘겨요. 리눅스 파이프와 같은 개념이에요."),
            ("Chain", "여러 Runnable을 이어 붙인 실행 묶음. 실행 순서가 미리 고정돼 있어요."),
            ("dict 입력", "체인의 첫 입력은 보통 {\"question\": \"...\"} 같은 딕셔너리예요. 키 이름이 프롬프트의 빈칸 이름과 맞아야 해요."),
            ("PromptTemplate", "빈칸({question})이 있는 프롬프트 틀. dict를 받아 빈칸을 채운 완성된 프롬프트를 만들어요. 채팅용은 ChatPromptTemplate."),
            ("ChatModel", "메시지 목록을 입력받아 메시지로 답하는 대화형 LLM 래퍼."),
            ("AIMessage", "ChatModel이 돌려주는 응답 객체. 본문(.content) 외에 메타데이터도 들어 있어서 그냥 문자열이 아니에요."),
            ("StrOutputParser", "AIMessage에서 본문 문자열만 뽑아 str로 바꿔 주는 파서."),
            ("RunnableLambda", "내가 만든 일반 파이썬 함수를 Runnable로 감싸 체인 중간에 끼울 수 있게 해 줘요. 예: RunnableLambda(clean_text)"),
            ("RunnablePassthrough", "입력을 손대지 않고 그대로 다음 단계로 넘겨요. RAG에서 검색은 하면서 원래 질문도 같이 들고 갈 때 써요."),
            ("invoke()", "Runnable이나 그래프를 실제로 한 번 실행하는 메서드."),
        ],
        "code": 'chain = prompt | model | parser\n\nrag_chain = (\n    {"context": retriever, "question": RunnablePassthrough()}\n    | prompt\n    | model\n    | StrOutputParser()\n)\nrag_chain.invoke("ELS의 위험은 무엇인가?")',
        "flow": "dict 입력 → PromptTemplate → ChatModel → AIMessage → StrOutputParser → str",
    },
    {
        "id": "rag_index",
        "title": "RAG 사전 준비 (인덱싱)",
        "icon": ":material/inventory_2:",
        "intro": "질문이 오기 전에 문서를 검색 가능한 형태로 미리 만들어 두는 단계예요.",
        "terms": [
            ("Document", "LangChain의 문서 단위. page_content(본문)와 metadata(출처, 페이지 번호 등)를 가져요."),
            ("Loader (Document Loader)", "PDF, 웹페이지, txt 같은 원본 파일을 읽어 Document 객체로 바꿔 줘요. 예: PyPDFLoader"),
            ("Text Cleaning", "불필요한 공백, 머리말/꼬리말, 깨진 문자 등을 지워서 검색 품질을 높이는 전처리."),
            ("Chunking", "긴 문서를 검색하기 좋은 작은 조각으로 자르는 일. 통째로 검색하면 질문과 상관없는 내용까지 섞이고, LLM에 넣을 수 있는 길이에도 한계가 있어서 잘라요."),
            ("Chunk", "잘라 낸 조각 하나. 검색과 저장의 기본 단위예요."),
            ("RecursiveCharacterTextSplitter", "가장 많이 쓰는 청킹 클래스. 문단(\\n\\n) → 줄(\\n) → 공백 → 글자 순으로 큰 단위부터 잘라 보면서 의미 덩어리를 최대한 유지해요."),
            ("chunk_size", "조각 하나의 최대 길이(예: 1000자). 너무 크면 잡음이 섞이고, 너무 작으면 문맥이 끊겨요."),
            ("chunk_overlap", "이웃한 조각끼리 겹치게 둘 길이(예: 150자). 경계에서 문장이 잘려 의미가 사라지는 걸 막아 줘요."),
            ("Embedding", "텍스트를 의미를 반영한 숫자 벡터로 바꾸는 일(또는 그 모델). 뜻이 비슷한 문장은 벡터도 서로 가까워져요."),
            ("Vector (벡터)", "[0.12, -0.44, 0.88, ...] 같은 숫자 배열. 의미 공간에서의 좌표라고 보면 돼요."),
            ("Vector DB", "벡터를 저장해 두고 '이 벡터와 가장 가까운 것'을 빠르게 찾아 주는 데이터베이스. 예: FAISS, Chroma, Pinecone. 의미 기반 자료 창고예요."),
        ],
        "code": "RecursiveCharacterTextSplitter(\n    chunk_size=1000,\n    chunk_overlap=150,\n)",
        "flow": "PDF / 문서 → Loader → Text Cleaning → Chunking → Embedding → Vector DB 저장",
    },
    {
        "id": "rag_query",
        "title": "RAG 질문 처리 (검색 + 생성)",
        "icon": ":material/manage_search:",
        "intro": "질문이 들어올 때마다 실행되는 단계예요. 답이 틀리면 검색 오류인지 생성 오류인지부터 나눠 봐요.",
        "terms": [
            ("질문 Embedding", "사용자 질문도 문서와 같은 임베딩 모델로 벡터로 바꿔요. 그래야 문서 벡터와 비교할 수 있어요."),
            ("유사도 검색", "질문 벡터와 가까운(코사인 유사도 등) 청크 벡터를 찾는 과정."),
            ("Retriever", "검색 과정을 감싼 인터페이스. retriever.invoke(질문) → 관련 Document 목록. 도서관 사서 역할이에요."),
            ("Reranking", "1차 검색 결과(예: 20개)를 더 정밀한 모델로 다시 점수 매겨 진짜 관련 높은 것을 위로 올리는 단계. 벡터 검색은 빠르지만 대략적이라서 보완해요."),
            ("Context", "찾아온 청크들을 프롬프트의 {context} 자리에 끼워 넣은 근거 자료."),
            ("Generation", "Context와 질문이 들어간 프롬프트로 LLM이 답변을 만드는 단계. RAG의 G예요."),
            ("Answer", "최종 답변."),
            ("검색 오류", "엉뚱한 청크를 가져온 경우. 청킹, 임베딩, 검색 개수, Reranking을 손봐요."),
            ("생성 오류", "맞는 청크를 가져왔는데 LLM이 잘못 답한 경우. 프롬프트를 손보거나 모델을 바꿔요."),
        ],
        "flow": "사용자 질문 → 질문 Embedding → Vector DB 검색 → Retriever → 관련 Chunk → Prompt의 Context에 삽입 → LLM → Answer",
    },
    {
        "id": "why_graph",
        "title": "LangGraph가 필요한 이유",
        "icon": ":material/alt_route:",
        "intro": "'다음에 무엇을 실행할지'가 단순 직선이 아닐 때 전체 흐름을 명확하게 설계하려고 써요.",
        "terms": [
            ("조건 / 분기", "\"검색이 필요한가?\"에 따라 길이 갈라지는 것."),
            ("반복 (루프)", "결과가 부족하면 앞 단계로 돌아가서 다시 실행하는 것."),
            ("재시도", "실패한 단계를 조건을 바꿔 다시 실행하는 것(예: 질문을 바꿔서 재검색)."),
            ("병렬 실행", "여러 작업을 동시에 실행하는 것(예: 웹 검색과 Vector DB 검색을 동시에)."),
            ("Graph (그래프)", "점(Node)과 선(Edge)으로 이루어진 구조. 업무 프로세스 설계도라고 생각하면 돼요."),
        ],
        "flow": "질문\n ↓\n검색이 필요한가?\n ├─ YES → 검색 → 결과가 충분한가?\n │           ├─ YES → 답변 생성\n │           └─ NO  → 질문 수정 → 재검색\n └─ NO  → 바로 답변",
    },
    {
        "id": "graph_core",
        "title": "State / Node / Edge",
        "icon": ":material/account_tree:",
        "intro": "State = 가방, Node = 작업실, Edge = 작업실 사이의 길.",
        "terms": [
            ("State", "그래프 전체가 들고 다니는 공유 데이터. 모든 Node가 같은 State를 읽고, 자기 결과를 State에 써요."),
            ("TypedDict", "파이썬 typing 기능으로 '이 딕셔너리에는 이런 키가 이런 타입으로 있다'고 미리 선언해요. LangGraph에서 State 구조를 정의할 때 써요."),
            ("Node", "실제로 일을 하는 단위로, 보통 파이썬 함수예요. State를 받아서 바꿀 부분만 dict로 돌려줘요."),
            ("부분 업데이트", "Node는 State 전체가 아니라 바꿀 키만 돌려줘요(예: {\"context\": docs}). LangGraph가 이걸 기존 State에 합쳐 줘요."),
            ("Edge", "Node 다음에 어느 Node로 갈지 정하는 연결선."),
        ],
        "code": 'from typing import TypedDict\n\nclass State(TypedDict):\n    question: str\n    context: list\n    answer: str\n\ndef retrieve_node(state):\n    question = state["question"]        # 가방에서 질문 꺼내기\n    docs = retriever.invoke(question)   # 검색하기\n    return {"context": docs}            # 바뀐 부분만 돌려주기',
    },
    {
        "id": "graph_build",
        "title": "Edge 종류와 그래프 조립",
        "icon": ":material/build:",
        "intro": "State 정의 → StateGraph 생성 → add_node → add_edge / add_conditional_edges → compile() → invoke()",
        "terms": [
            ("add_edge()", "일반 Edge. add_edge(\"retrieve\", \"generate\")면 항상 retrieve 다음에 generate. 고정된 길이에요."),
            ("add_conditional_edges()", "조건부 Edge. 앞 Node가 끝나면 라우팅 함수를 실행해 그 반환값에 따라 다음 Node가 달라져요. 갈림길이에요."),
            ("route_fn (라우팅 함수)", "State를 보고 다음에 갈 곳을 문자열로 돌려주는 함수. 예: 검색이 필요하면 \"search\", 아니면 \"direct\". 세 번째 인자로 {\"search\": \"retrieve\", \"direct\": \"generate\"} 같은 매핑을 줄 수 있어요."),
            ("START / END", "그래프의 시작점과 끝점을 나타내는 특수 노드. END로 가면 실행이 끝나요."),
            ("StateGraph", "State 타입을 받아 그래프를 설계하는 빌더 클래스. builder = StateGraph(State)"),
            ("builder", "아직 설계 중인 그래프 객체를 담는 변수 이름(관례). 여기에 Node와 Edge를 등록해요."),
            ("add_node()", "Node 등록. add_node(\"이름\", 함수)"),
            ("compile()", "설계도를 검사하고 실행 가능한 그래프 객체로 바꿔요. 컴파일된 그래프도 Runnable이라서 invoke()를 쓸 수 있어요."),
            ("invoke() (그래프)", "초기 State(예: {\"question\": \"...\"})를 넣어 그래프를 끝까지 실행하고 최종 State를 돌려받아요."),
        ],
        "code": 'builder = StateGraph(State)\nbuilder.add_node("check", check_node)\nbuilder.add_node("retrieve", retrieve_node)\nbuilder.add_node("generate", generate_node)\n\nbuilder.add_edge(START, "check")\nbuilder.add_conditional_edges(\n    "check", route_fn,\n    {"search": "retrieve", "direct": "generate"},\n)\nbuilder.add_edge("retrieve", "generate")\nbuilder.add_edge("generate", END)\n\ngraph = builder.compile()\ngraph.invoke({"question": "ELS의 위험은?"})',
    },
    {
        "id": "parallel",
        "title": "병렬 실행과 Reducer",
        "icon": ":material/call_split:",
        "intro": "Fan-out으로 갈라지고 Fan-in으로 모이며, 같은 키를 동시에 쓰면 Reducer가 합치는 규칙을 정해요.",
        "terms": [
            ("Fan-out", "하나의 Node에서 여러 Node로 동시에 갈라져 나가는 것. 부채(fan)가 펼쳐지는 모양이에요."),
            ("Fan-in", "갈라졌던 여러 Node의 결과가 하나의 Node로 다시 모이는 것. 합치는 Node는 앞의 병렬 작업이 모두 끝난 뒤 실행돼요."),
            ("Crossfade (함정)", "영상/오디오가 겹치며 전환되는 효과를 뜻하는 용어라 LangGraph와 관계없어요. 병렬 합류는 Fan-in이에요."),
            ("Reducer", "여러 Node가 같은 State 키를 업데이트할 때 값을 어떻게 합칠지 정하는 규칙. 지정하지 않으면 기본은 덮어쓰기라서 병렬 결과가 사라지거나 충돌 에러가 나요."),
            ("Annotated", "typing 기능으로 타입에 추가 정보를 붙여요. Annotated[list, operator.add] = 타입은 list이고 합칠 때는 operator.add를 써라."),
            ("operator.add", "파이썬의 + 연산을 함수로 만든 것. 리스트에 쓰면 [\"A\"] + [\"B\"] = [\"A\", \"B\"]처럼 이어 붙여요."),
        ],
        "code": "import operator\nfrom typing import Annotated, TypedDict\n\nclass State(TypedDict):\n    results: Annotated[list, operator.add]\n\n# Node A → {\"results\": [\"A\"]}\n# Node B → {\"results\": [\"B\"]}\n# 최종 results → [\"A\", \"B\"]",
        "flow": "              → 검색 A →\n질문 분석 Node               → 합치기 Node\n              → 검색 B →\n(Fan-out)                   (Fan-in)",
    },
    {
        "id": "loop",
        "title": "반복 · 재시도 · 검증",
        "icon": ":material/autorenew:",
        "intro": "한 번 실행하고 끝나는 Chain과 달리 LangGraph는 자기검증과 재시도 루프를 자연스럽게 만들 수 있어요.",
        "terms": [
            ("답변 검증", "생성된 답변이 근거 문서와 맞는지, 형식이 맞는지 확인하는 Node."),
            ("루프", "검증 결과가 '부족함'이면 conditional edge로 앞 Node(질문 수정 → 검색)로 되돌아가고, '좋음'이면 END로 가요."),
            ("자기검증", "사람이 아니라 시스템(LLM)이 자기 결과를 다시 평가하는 구조."),
            ("최대 반복 횟수", "State에 retry_count 같은 값을 두고 상한을 넘으면 END로 보내 무한 반복을 막아요."),
        ],
        "flow": "질문 → 검색 → 답변 생성 → 답변 검증\n                         ├─ 좋음   → END\n                         └─ 부족함 → 질문 수정 → 다시 검색",
    },
    {
        "id": "checkpoint",
        "title": "Checkpoint · Memory · Human-in-the-loop",
        "icon": ":material/save:",
        "intro": "State를 저장해 두면 멈췄다 이어서 실행하고, 대화를 기억하고, 사람 승인을 기다릴 수 있어요.",
        "terms": [
            ("Checkpoint", "그래프 실행 중 각 단계의 State를 저장한 스냅샷. 중간에 멈췄다가 이어서 실행하거나 오류 시 복구할 수 있어요. compile(checkpointer=...)로 저장소를 붙여요."),
            ("checkpointer", "Checkpoint를 실제로 저장하는 저장소. 메모리, SQLite 등을 고를 수 있어요."),
            ("thread_id", "같은 대화를 구분하는 ID. 같은 thread_id로 실행하면 이전 State를 이어받아요."),
            ("Memory", "Checkpoint 덕분에 같은 대화의 이전 State가 남아서 맥락이 유지되는 것. 챗봇이 앞에서 한 말을 기억하는 원리예요."),
            ("Human-in-the-loop", "흐름 중간에 사람의 확인을 끼워 넣는 구조. AI 초안 → 사람 승인? → 예: 다음 단계 / 아니오: 수정 Node. 멈춘 State를 Checkpoint로 보관하다가 사람이 응답하면 그 지점부터 다시 실행해요."),
        ],
    },
    {
        "id": "agent",
        "title": "Agent",
        "icon": ":material/smart_toy:",
        "intro": "고정 Chain은 개발자가 순서를 정하고, Workflow는 개발자가 조건을 설계하고, Agent는 LLM이 다음 행동을 판단해요.",
        "terms": [
            ("Agent", "다음에 어떤 행동을 할지를 LLM이 상황을 보고 스스로 판단하는 구조. 행동 → 관찰 → 다시 판단을 반복해요."),
            ("Tool", "Agent가 호출할 수 있는 도구(함수). 검색 Tool, 계산기 Tool, DB 조회 Tool 등. LLM은 어떤 Tool을 어떤 인자로 부를지만 정하고, 실제 실행은 코드가 해요."),
            ("고정 Chain", "실행 순서를 개발자가 미리 다 정해 둔 구조. 항상 같은 순서로 실행돼요."),
            ("Workflow (LangGraph)", "개발자가 조건과 흐름을 설계하고, 그 안에서 조건에 따라 길이 갈려요."),
            ("Multi-agent", "여러 Agent가 역할을 나눠 협업하는 구조(Research / Coding / Review Agent)."),
            ("Manager Agent", "사용자 요청을 받아 하위 Agent들에게 일을 나눠 주고 결과를 합치는 총괄 Agent. Supervisor라고도 해요."),
        ],
    },
    {
        "id": "graph_rag",
        "title": "LangGraph + RAG 응용",
        "icon": ":material/psychology:",
        "intro": "RAG가 '무엇을 검색해서 답할지'라면 LangGraph는 '검색을 언제, 몇 번, 어떤 조건에서 할지'를 제어해요.",
        "terms": [
            ("질문 분석", "질문의 의도와 유형을 파악하는 첫 Node."),
            ("검색 필요 판단", "문서 없이 바로 답할 수 있는지 판단해서 불필요한 검색을 줄여요(비용, 속도 절약)."),
            ("문서 충분성 판단", "가져온 문서가 질문에 답하기에 충분한지 평가해요."),
            ("Query Rewrite", "검색이 잘 안 될 때 질문을 검색하기 좋은 형태로 고쳐 쓰는 것. 예: \"그거 위험해?\" → \"ELS 상품의 주요 투자 위험 요소\""),
            ("재검색", "고쳐 쓴 질문으로 다시 검색하는 것."),
            ("Faithfulness 검사", "답변이 가져온 근거 문서에 충실한지(근거에 없는 내용을 지어내지 않았는지, 즉 환각 여부) 확인하는 검사."),
            ("재생성", "Faithfulness 검사를 통과하지 못하면 답변을 다시 생성하는 것."),
        ],
    },
    {
        "id": "examples",
        "title": "실전 응용 예시 용어",
        "icon": ":material/apps:",
        "intro": "실제 서비스에서는 분기(라우팅)와 재시도 루프가 거의 항상 등장해요.",
        "terms": [
            ("문의 유형 분류 (라우팅)", "고객 상담 챗봇에서 질문을 배송, 환불, 일반으로 나눠 각각 배송 DB, 정책 문서 RAG, 일반 LLM으로 보내요. conditional edge의 대표 쓰임이에요."),
            ("위험 요소 분석 / 보고서 생성", "문서 분석 시스템의 Node들. 근거가 부족하면 추가 검색으로 돌아가는 루프가 있어요."),
            ("문법 분석 / 버그 탐지 / 보안 검사 / 테스트", "코드 리뷰 Agent의 Node들. 테스트가 실패하면 수정 Node로 돌아가는 재시도 루프예요."),
            ("강화학습", "보상(Reward)을 최대화하도록 행동을 학습하는 머신러닝 방식."),
            ("Reward 분석", "강화학습에서 보상 설계가 잘못돼 학습이 이상해졌는지 점검하는 것."),
            ("Exploration 분석", "에이전트가 새로운 행동을 충분히 시도(탐험)하는지 점검하는 것. 탐험이 부족하면 한 가지 행동에만 갇혀요."),
        ],
    },
]

ANALOGIES = [
    ("LangChain", "LLM 부품 연결", "레고 부품과 연결 방식"),
    ("RAG", "외부 지식 검색", "책 찾아보고 답하기"),
    ("Vector DB", "벡터 저장/검색", "의미 기반 자료 창고"),
    ("Retriever", "관련 자료 가져오기", "도서관 사서"),
    ("LangGraph", "실행 흐름 제어", "업무 프로세스 설계도"),
    ("State / Node / Edge", "공유 데이터 / 작업 / 연결", "가방 / 작업실 / 길"),
    ("Agent", "다음 행동 판단", "상황 보고 스스로 결정하는 작업자"),
]

CONFUSING_PAIRS = [
    ("RunnableLambda", "함수를 Runnable로 실행", "RunnablePassthrough", "입력을 그대로 유지"),
    ("add_edge", "항상 같은 다음 Node", "add_conditional_edges", "조건에 따라 다른 Node"),
    ("Fan-in", "여러 개 → 하나 합류", "Crossfade", "영상/오디오 용어 (오답)"),
    ("Reducer", "병렬 결과 병합 규칙", "Checkpoint", "State 저장/복구"),
    ("고정 Chain", "개발자가 순서 결정", "Agent", "LLM이 다음 행동 결정"),
]
